spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/feelinsight?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 2356
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    backend:
      url: http://localhost:8000
#    database-platform:

django:
  server:
    url: http://localhost:8000